---
title: "Myc paper"
author: "Shruti"
date: "11/11/2022"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
library(Seurat)
library(patchwork)
library(ggplot2)
```



```{r}
#Read in data and annotate with cell and study 

annot <- read.csv("~/Downloads/AnnotationBcells.csv")
annot <- data.frame(annot,do.call(rbind,str_split(annot$Sample,";")))
annot <- annot[,-c(1)]
colnames(annot) <- c("Sample", "Barcode", "Population")

dlbc.l1 <- Read10X(data.dir="~/Desktop/sc-RNASeq/heiDATA/DLBCL1/")
l1 <- CreateSeuratObject(counts = dlbc.l1, project = "L1", min.cells = 3, min.features = 200)
l1@meta.data$study <- "Roider"
annot_l1 <- annot %>% dplyr::filter(Population == "MalignantB" & Sample == "DLBCL1")
annot_l1$Barcode <- paste0( annot_l1$Barcode, "-1")
l1_b <- subset(l1, cells = annot_l1$Barcode)
l1_b@meta.data$annotation <- annot_l1$Population
l1_b@meta.data$COO <- "GCB"

dlbc.l3 <- Read10X(data.dir="~/Desktop/sc-RNASeq/heiDATA/DLBCL3/")
l3 <- CreateSeuratObject(counts = dlbc.l3, project = "L3", min.cells = 3, min.features = 200)
l3@meta.data$study <- "Roider"
annot_l3 <- annot %>% dplyr::filter(Population == "MalignantB" & Sample == "DLBCL3")
annot_l3$Barcode <- paste0( annot_l3$Barcode, "-1")
l3_b <- subset(l3, cells = annot_l3$Barcode)
l3_b@meta.data$annotation <- annot_l3$Population
l3_b@meta.data$COO <- "ABC"

dat=fread( "~/Desktop/sc-RNASeq/Ash /GSE182434_raw_count_matrix.txt.gz",data.table = F)  
dim(dat) 
dat[1:4,1:4]
rownames(dat)=dat[,1]
dat=dat[,-1]
dat[1:4,1:4] 
annotation = fread( "~/Desktop/sc-RNASeq/Ash /GSE182434_cell_annotation.txt.gz",data.table = F)
annotation[1:4,1:4]
table(annotation$Patient,annotation$CellType) 
sample = c("DLBCL002","DLBCL007","DLBCL008","DLBCL111")
annotation = annotation[annotation$Patient %in% sample,]
dat = dat[,annotation$ID]


l4 <- CreateSeuratObject(counts = dat, project = "L4", min.cells = 3, min.features = 200)
l4@meta.data$annotation <- annotation$CellType
l4@meta.data$type <- annotation$TumorNormal
l4@meta.data$COO <- annotation$COO
l4_b <- subset(l4, annotation == "B cells")
l4_bm <- subset(l4_b, type == "Tumor")
l4_bm@meta.data$study <- "Steen"





```

```{r}
#Merge datasets 

m26 <- merge(x=l1_b, y=c(l3_b,l4_bm), add.cell.ids=c("L1","L3", "L4"), merge.data=T, project="LymphNodes")



```

```{r}
#Preprocesing

m26[["percent.mt"]] <- PercentageFeatureSet(m26, pattern = "^MT-")
VlnPlot(m26, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
m26 = NormalizeData(m26, normalization.method = "LogNormalize", scale.factor = 10000)
m26 = FindVariableFeatures(m26)
m26 = ScaleData(m26, vars.to.regress = c("nFeature_RNA", "percent.mt"))
m26 = RunPCA(m26, npcs = 20)
m26 = RunUMAP(m26, dims = 1:10)

```

```{r}
#Batch integration

m26.list <- SplitObject(m26, split.by="study")

m26.list <- lapply(X = m26.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 5000)
})
features <- SelectIntegrationFeatures(object.list = m26.list)
immune.anchors <- FindIntegrationAnchors(object.list = m26.list,
                                         anchor.features = features)
immune.combined <- IntegrateData(anchorset = immune.anchors)

DefaultAssay(immune.combined) <- "integrated"
# Run the standard workflow for visualization and clustering
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:15)

DimPlot(immune.combined, reduction = "umap", group.by = "study")


```

```{r}
#Plotting cells 

pos_ids   <- WhichCells(m26, expression= (MYC>0 & BCL2 >0 & BCL6==0), slot="count")
pos_cells <- subset(m26,cells=pos_ids)
pos_cells@meta.data['m26_status'] <- "M+2+6-"

neg_ids = colnames(m26)[!(colnames(m26) %in% pos_ids)]
neg_cells <- subset(m26, cells = neg_ids)
neg_cells@meta.data['m26_status'] <- "all"

m26_myc <- merge(x=pos_cells, y=c(neg_cells),add.cell.ids=c("P","N"), merge.data = T, project = "rLymphNode")
Idents(m26_myc) <- 'm26_status'
head(x = Idents(object = m26_myc))
m26_myc <- NormalizeData(m26_myc, normalization.method = "LogNormalize", scale.factor = 10000)
m26_myc <- ScaleData(m26_myc)



```

```{r}
#Plot Mp2p6n

raw_ex2 <- GetAssayData(object = m26, slot = "counts")[c("MYC", "BCL2", "BCL6"),]


raw_ex <- FetchData(m26, vars = c("MYC", "BCL2", "BCL6"))
raw_2bin <- raw_ex
raw_2bin[raw_2bin > 0 ] <- 1
raw_2bin <- cbind(raw_2bin,
                  Mp2p6n = ifelse(raw_2bin[,1] == 1 &
                                    raw_2bin[,2] == 1 & 
                                    raw_2bin[,3] == 0,
                                  1,
                                  0))


immune.combined <- AddMetaData(immune.combined,
                                 raw_2bin$Mp2p6n,
                                 col.name = "Mp2p6n") 

FeaturePlot(immune.combined, features = "Mp2p6n")
```




```{r}
#DEG's

DEG.markers <- FindMarkers(m26_myc, ident.1 = "M+2+6-", ident.2 = "all")
write.csv(DEG.markers,"~/Desktop/Myc paper /DEG.csv",quote=F,row.names = T)


```

```{r}
#Pathway analysis 

library(escape)

#sce <- as.SingleCellExperiment(m26_myc, assay = "RNA")
GS.hallmark <- getGeneSets(library = c("H", "C6", "C2", "C7", "C4", "C8"))
ES.seurat <- enrichIt(obj = m26_myc, gene.sets = GS.hallmark)
ES.seurat$COO <- m26_myc@meta.data$COO
ES.seurat$m26_status <- m26_myc@meta.data$m26_status
output <- getSignificance(ES.seurat, group = "m26_status", fit = "T.test")
write.csv(output, "~/Desktop/Myc paper /T_statistic_hallmark_all.csv")


#C2
#GS.hallmark <- getGeneSets(library = c("H", "C6", "C2", "C7", "C4", "C8"))
ES.C2 <- enrichIt(obj = m26_myc, gene.sets = GS.C2)
ES.C2$COO <- m26_myc@meta.data$COO
ES.C2$m26_status <- m26_myc@meta.data$m26_status
output <- getSignificance(ES.C2, group = "m26_status", fit = "T.test")
write.csv(output, "~/Desktop/Myc paper /T_statistic_C2_all.csv")

#C7

```

```{r}
#Visualisation 

m26_myc <- Seurat::AddMetaData(m26_myc, ES.seurat)

library(dittoSeq)
colors <- colorRampPalette(c("#0D0887FF","#7E03A8FF","#CC4678FF","#F89441FF","#F0F921FF"))
dittoHeatmap(m26_myc, genes = NULL, metas = names(ES.seurat), 
             annot.by = "m26_status", 
             fontsize = 7, 
             cluster_cols = F,
             heatmap.colors = colors(50), order.by = "m26_status")

```

```{r}
#Find clusters


immune.combined <- FindNeighbors(immune.combined, dims = 1:15)
immune.combined <- FindClusters(immune.combined, resolution = 0.5)
DimPlot(immune.combined, reduction = "umap")


```

```{r}
#double positive vs triple postitive 

pos_ids   <- WhichCells(m26, expression= (MYC>0 & BCL2 >0 & BCL6==0), slot="count")
pos_cells <- subset(m26,cells=pos_ids)
pos_cells@meta.data['m26_status'] <- "M+2+6-"

neg_ids <- WhichCells(m26, expression= (MYC>0 & BCL2 >0 & BCL6> 0), slot="count")
#neg_ids = colnames(m26)[!(colnames(m26) %in% pos_ids)]
neg_cells <- subset(m26, cells = neg_ids)
neg_cells@meta.data['m26_status'] <- "triple positive"

m26_myc_triple <- merge(x=pos_cells, y=c(neg_cells),add.cell.ids=c("P","N"), merge.data = T, project = "rLymphNode")
Idents(m26_myc_triple) <- 'm26_status'
head(x = Idents(object = m26_myc_triple))
m26_myc_triple <- NormalizeData(m26_myc_triple, normalization.method = "LogNormalize", scale.factor = 10000)
m26_myc_triple <- ScaleData(m26_myc_triple)

DEG.markers_triple <- FindMarkers(m26_myc_triple, ident.1 = "M+2+6-", ident.2 = "triple positive")



```

```{r}
#Overlay double and triple postive on umap 

DimPlot(immune.combined, group.by = "myc_status", reduction = "umap", cols = c("Yellow", "Grey", "Maroon"))
raw_ex3 <- GetAssayData(object = m26, slot = "counts")[c("MYC", "BCL2", "BCL6"),]


raw_ex_1 <- FetchData(m26, vars = c("MYC", "BCL2", "BCL6"))
raw_2bin_1 <- raw_ex_1
raw_2bin_1[raw_2bin_1 > 0 ] <- 1
raw_2bin_1 <- cbind(raw_2bin_1,
                  myc_status = ifelse(raw_2bin_1[,1] == 1 &
                                    raw_2bin_1[,2] == 1 & 
                                    raw_2bin_1[,3] == 1,
                                  "triple positive", ifelse(raw_2bin_1[,1] == 1 & raw_2bin_1[,2] == 1 & raw_2bin_1[,3] == 0, "double positive", "others")))
              
immune.combined <- AddMetaData(immune.combined,
                                 raw_2bin_1$myc_status,
                                 col.name = "myc_status") 

```

```{r}
#Lymph2cx 

ABC_lymph2cx <- c("TNFRSF3B", "LIMD1", "IRF4", "CREB3L2", "PIM2", "CYB5R2", "RAB29", "CCDC50")
GCB_lymph2cx <- c("MME", "SERPINA9", "ASB13", "MAML3","ITPKB","MYBL1","SIPR2")
FeaturePlot(immune.combined, features = ABC_lymph2cx)

FeaturePlot(immune.combined, features = GCB_lymph2cx)




```


```{r}
#ABC and GCB Mp2p6n vs all 

m26_abc <- subset(m26, subset = COO == "ABC")
m26_gcb <- subset(m26, subset = COO == "GCB")

pos_ids   <- WhichCells(m26_abc, expression= (MYC>0 & BCL2 >0 & BCL6==0), slot="count")
pos_cells <- subset(m26_abc,cells=pos_ids)
pos_cells@meta.data['m26_status'] <- "M+2+6-"

neg_ids = colnames(m26_abc)[!(colnames(m26_abc) %in% pos_ids)]
neg_cells <- subset(m26_abc, cells = neg_ids)
neg_cells@meta.data['m26_status'] <- "others"

m26_abc_all <- merge(x=pos_cells, y=c(neg_cells),add.cell.ids=c("P","N"), merge.data = T, project = "rLymphNode")
Idents(m26_abc_all) <- 'm26_status'
head(x = Idents(object = m26_abc_all))
m26_abc_all <- NormalizeData(m26_abc_all, normalization.method = "LogNormalize", scale.factor = 10000)
m26_abc_all <- ScaleData(m26_abc_all)

DEG.markers_triple <- FindMarkers(m26_abc_all, ident.1 = "M+2+6-", ident.2 = "others")





```


```{r}
#GSEA 

## Mp2p6n vs all 


markers <- FindMarkers(m26_myc, ident.1 = "M+2+6-", ident.2 = "all", logfc.threshold = 0, min.pct = 0, test.use="MAST")

ranks <- markers$avg_logFC
names(ranks) <- rownames(markers)

m_df<- msigdbr(species = "Homo sapiens", category = "H")
fgsea_sets<- m_df %>% split(x = .$gene_symbol, f = .$gs_name)

# allPathways is predefined list of signatures
fgseaRes <- fgsea(pathways = fgsea_sets, 
                  stats = ranks,
                  minSize=10,
                  maxSize=500,
                  nperm=1000000)

#commitsdlmao
#will this work 
```

